const {onRequest}=require("firebase-functions/v2/https");
const {defineSecret}=require("firebase-functions/params");
const {initializeApp}=require("firebase-admin/app");
const {getAuth}=require("firebase-admin/auth");
const {getStorage}=require("firebase-admin/storage");
const {createClient}=require("@supabase/supabase-js");
const express=require("express"),crypto=require("crypto"),Busboy=require("busboy");
const SUPABASE_URL=defineSecret("SUPABASE_URL"),SUPABASE_SERVICE_ROLE_KEY=defineSecret("SUPABASE_SERVICE_ROLE_KEY");
initializeApp();const app=express();app.use(express.json({limit:"1mb"}));
const fail=(res,status,message,code="REQUEST_ERROR")=>res.status(status).json({success:false,error:{message,code}});
const db=()=>createClient(SUPABASE_URL.value(),SUPABASE_SERVICE_ROLE_KEY.value(),{auth:{autoRefreshToken:false,persistSession:false}});
const email=v=>String(v||"").trim().toLowerCase(),hash=v=>crypto.createHash("sha256").update(v).digest("hex");
async function audit(user,action,metadata={},resource="OFFICER"){const {error}=await db().from("audit_logs").insert({user_uid:user.uid,user_email:user.email,action,resource,status:"success",metadata});if(error)throw error}
async function officer(req,res,next){const header=req.get("authorization")||"";if(!header.startsWith("Bearer "))return fail(res,401,"Authentication is required.","UNAUTHENTICATED");try{const token=await getAuth().verifyIdToken(header.slice(7));const {data,error}=await db().from("officers").select("*").eq("firebase_uid",token.uid).maybeSingle();if(error)throw error;if(!data?.is_active)return fail(res,403,"This account is not an authorized officer.","FORBIDDEN");req.officer={uid:token.uid,email:token.email||data.email,profile:data};next()}catch(error){console.error("Authentication lookup failed",error);return fail(res,401,"Your session is invalid or expired.","UNAUTHENTICATED")}}
const admin=(req,res,next)=>req.officer.profile.role==="SUPER_ADMIN"?next():fail(res,403,"Administrator access is required.","FORBIDDEN");
const owns=(row,user)=>row.officer_uid===user.uid||user.profile.role==="SUPER_ADMIN";
app.get("/health",async(_req,res)=>{const {error}=await db().from("officers").select("firebase_uid",{head:true}).limit(1);return error?fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE"):res.json({success:true,data:{service:"firebase-functions",database:"supabase-postgresql"}})});
app.post("/auth/register",async(req,res)=>{const {token,password,password_confirmation}=req.body||{},e=email(req.body?.email);if(!/^\S+@\S+\.\S+$/.test(e)||!token||!password||!password_confirmation)return fail(res,400,"Email, invitation token, password, and confirmation are required.","VALIDATION_ERROR");if(password!==password_confirmation)return fail(res,400,"Passwords do not match.","VALIDATION_ERROR");if(password.length<12)return fail(res,400,"Use a password of at least 12 characters.","VALIDATION_ERROR");const client=db(),{data:invite,error:lookup}=await client.from("officer_invitations").select("id,status,expires_at").eq("email",e).eq("token_hash",hash(token)).maybeSingle();if(lookup)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");if(!invite||invite.status!=="PENDING"||new Date(invite.expires_at)<=new Date())return fail(res,422,"The invitation is invalid or expired.","INVALID_INVITATION");let user;try{user=await getAuth().createUser({email:e,password,emailVerified:false})}catch(error){return error.code==="auth/email-already-exists"?fail(res,409,"An account already exists for this official email.","CONFLICT"):fail(res,503,"Authentication service is unavailable.","AUTH_UNAVAILABLE")}const {error}=await client.rpc("accept_officer_invitation",{p_invitation_id:invite.id,p_uid:user.uid,p_email:e});if(error){await getAuth().deleteUser(user.uid).catch(()=>{});console.error("Invitation acceptance failed",error);return fail(res,500,"Registration could not be completed.","DATABASE_ERROR")}res.status(201).json({success:true,data:{email:e}})});
app.post("/auth/login",officer,async(req,res)=>{await audit(req.officer,"LOGIN");res.json({success:true,data:{email:req.officer.email,role:req.officer.profile.role}})});
app.post("/auth/logout",officer,async(req,res)=>{await audit(req.officer,"LOGOUT");res.json({success:true,data:null})});app.get("/auth/me",officer,(req,res)=>res.json({success:true,data:{email:req.officer.email,role:req.officer.profile.role,is_active:true}}));
app.get("/officers",officer,admin,async(_req,res)=>{const {data,error}=await db().from("officers").select("*").order("created_at",{ascending:false});if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");res.json({success:true,data:data.map(x=>({id:x.firebase_uid,email:x.email,role:x.role,is_active:x.is_active,created_at:x.created_at,last_login:null}))})});
app.post("/officers/invite",officer,admin,async(req,res)=>{const e=email(req.body?.email);if(!/^\S+@\S+\.\S+$/.test(e))return fail(res,400,"Enter a valid official email.","VALIDATION_ERROR");const token=crypto.randomBytes(32).toString("base64url"),{data,error}=await db().from("officer_invitations").insert({email:e,token_hash:hash(token),created_by:req.officer.uid,expires_at:new Date(Date.now()+6048e5).toISOString()}).select("id,email,expires_at").single();if(error)return error.code==="23505"?fail(res,409,"An invitation already exists for this email.","CONFLICT"):fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");await audit(req.officer,"OFFICER_INVITED",{email:e});res.status(201).json({success:true,data:{...data,token}})});
app.post("/officers/:uid/:action",officer,admin,async(req,res)=>{const action=req.params.action;if(!["activate","deactivate","revoke"].includes(action))return fail(res,422,"Invalid officer action.","VALIDATION_ERROR");const {data:target}=await db().from("officers").select("*").eq("firebase_uid",req.params.uid).maybeSingle();if(!target)return fail(res,404,"Officer not found.","NOT_FOUND");if(target.role==="SUPER_ADMIN")return fail(res,403,"The official administrator cannot be modified here.","FORBIDDEN");const {data,error}=await db().from("officers").update({is_active:action==="activate"}).eq("firebase_uid",target.firebase_uid).select("*").single();if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");await audit(req.officer,`OFFICER_${action.toUpperCase()}`,{email:target.email});res.json({success:true,data:{id:data.firebase_uid,email:data.email,role:data.role,is_active:data.is_active,created_at:data.created_at,last_login:null}})});
app.post("/verification",officer,async(req,res)=>{const bidder_name=String(req.body?.bidder_name||"").trim(),document_type=String(req.body?.document_type||"").trim();if(!bidder_name||!document_type)return fail(res,400,"Bidder name and document type are required.","VALIDATION_ERROR");const verification_id=`VER-${crypto.randomBytes(6).toString("hex").toUpperCase()}`,{data,error}=await db().from("verifications").insert({verification_id,bidder_name,document_type,officer_uid:req.officer.uid}).select("*").single();if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");await audit(req.officer,"VERIFICATION_REQUESTED",{verification_id});res.status(201).json({success:true,data})});
app.get("/verification",officer,async(req,res)=>{let q=db().from("verifications").select("*").order("created_at",{ascending:false}).limit(100);if(req.officer.profile.role!=="SUPER_ADMIN")q=q.eq("officer_uid",req.officer.uid);if(req.query.status)q=q.eq("status",req.query.status);if(req.query.document_type)q=q.eq("document_type",req.query.document_type);if(req.query.q)q=q.ilike("bidder_name",`%${req.query.q}%`);const {data,error}=await q;error?fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE"):res.json({success:true,data})});
app.post("/verification/:id",officer,async(req,res)=>{const client=db(),{data:old}=await client.from("verifications").select("*").eq("id",req.params.id).maybeSingle();if(!old)return fail(res,404,"Not found.","NOT_FOUND");if(!owns(old,req.officer))return fail(res,403,"Forbidden.","FORBIDDEN");const {data,error}=await client.from("verifications").update({status:"MANUAL_REVIEW",updated_at:new Date().toISOString()}).eq("id",old.id).select("*").single();if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");await audit(req.officer,"VERIFICATION_COMPLETED",{verification_id:old.verification_id,status:data.status});res.json({success:true,data})});
app.post("/verification/:id/upload",officer,async(req,res)=>{
 const {data:record}=await db().from("verifications").select("*").eq("id",req.params.id).maybeSingle();
 if(!record)return fail(res,404,"Not found.","NOT_FOUND");if(!owns(record,req.officer))return fail(res,403,"Forbidden.","FORBIDDEN");
 if(!(req.get("content-type")||"").startsWith("multipart/form-data"))return fail(res,400,"Upload a document using multipart form data.","INVALID_DOCUMENT");
 const chunks=[];let info;
 try{await new Promise((resolve,reject)=>{const parser=Busboy({headers:req.headers,limits:{files:1,fileSize:10485760}});parser.on("file",(_name,file,fileInfo)=>{info=fileInfo;file.on("data",chunk=>chunks.push(chunk));file.on("limit",()=>reject(new Error("TOO_LARGE")))});parser.on("error",reject);parser.on("finish",resolve);req.pipe(parser)})}catch{return fail(res,422,"Upload a PDF, JPG, JPEG, or PNG under 10 MB.","INVALID_DOCUMENT")}
 const bytes=Buffer.concat(chunks),allowed=new Set(["application/pdf","image/jpeg","image/png"]);
 if(!info||!allowed.has(info.mimeType)||!bytes.length)return fail(res,422,"Upload a PDF, JPG, JPEG, or PNG under 10 MB.","INVALID_DOCUMENT");
 const safe=info.filename.replace(/[^a-zA-Z0-9._-]/g,"_"),storage_path=`verification/${record.officer_uid}/${record.id}/${Date.now()}-${safe}`;
 await getStorage().bucket().file(storage_path).save(bytes,{contentType:info.mimeType,resumable:false});
 const {data,error}=await db().from("verification_documents").insert({verification_id:record.id,original_name:info.filename,mime_type:info.mimeType,size_bytes:bytes.length,sha256:hash(bytes),storage_path}).select("*").single();
 if(error)return fail(res,503,"Database write failed after upload; retry safely.","DATABASE_UNAVAILABLE");await audit(req.officer,"DOCUMENT_UPLOADED",{verification_id:record.verification_id,document:info.filename});res.status(201).json({success:true,data});
});
app.get("/settings",officer,async(req,res)=>{const {data,error}=await db().from("user_settings").select("*").eq("officer_uid",req.officer.uid).maybeSingle();error?fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE"):res.json({success:true,data:data||{full_name:"",job_title:"",notification_preferences:{email:true},ai_preferences:{concise:true},updated_at:null}})});
app.patch("/settings",officer,async(req,res)=>{const value={officer_uid:req.officer.uid,full_name:String(req.body?.full_name||""),job_title:String(req.body?.job_title||""),notification_preferences:req.body?.notification_preferences||{},ai_preferences:req.body?.ai_preferences||{},updated_at:new Date().toISOString()}, {data,error}=await db().from("user_settings").upsert(value,{onConflict:"officer_uid"}).select("*").single();error?fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE"):res.json({success:true,data})});
app.get("/audit",officer,admin,async(req,res)=>{let q=db().from("audit_logs").select("*",{count:"exact"}).order("created_at",{ascending:false});if(req.query.status)q=q.eq("status",req.query.status);if(req.query.search)q=q.ilike("action",`%${req.query.search}%`);const {data,error,count}=await q;if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");res.json({success:true,data:{results:data.map(x=>({id:x.id,user_email:x.user_email,action:x.action,event_type:x.resource,status:x.status,result:x.result,description:x.description,metadata:x.metadata,created_at:x.created_at})),count:count||0,page:1,total_pages:1}})});
app.get("/history",officer,async(req,res)=>{let q=db().from("audit_logs").select("*",{count:"exact"}).eq("user_uid",req.officer.uid).order("created_at",{ascending:false});if(req.query.status)q=q.eq("status",req.query.status);if(req.query.search)q=q.ilike("action",`%${req.query.search}%`);const {data,error,count}=await q;if(error)return fail(res,503,"Database is unavailable.","DATABASE_UNAVAILABLE");res.json({success:true,data:{results:data.map(x=>({id:x.id,action:x.action,event_type:x.resource,status:x.status,related_object:x.result||"",metadata:x.metadata,created_at:x.created_at})),count:count||0,page:1,total_pages:1}})});
app.use((_req,res)=>fail(res,404,"API endpoint not found.","NOT_FOUND"));exports.api=onRequest({region:"us-central1",cors:["https://gem-verify-one.vercel.app"],maxInstances:10,secrets:[SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY]},app);
