"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, Audit, Page } from "@/lib/api";

export default function AuditPage() {
  const [rows, setRows] = useState<Audit[]>([]), [selected, setSelected] = useState<Audit | null>(null), [q, setQ] = useState(""), [status, setStatus] = useState(""), [sort, setSort] = useState("-created_at"), [page, setPage] = useState(1), [loading, setLoading] = useState(true), [error, setError] = useState(""), [meta, setMeta] = useState({ count: 0, total_pages: 1 });
  useEffect(() => { let cancelled = false; void (async () => { try { const response = await api<Page<Audit>>(`/audit/?search=${encodeURIComponent(q)}&status=${status}&ordering=${sort}&page=${page}`); if (!cancelled) { setRows(response.data.results); setMeta(response.data); setError(""); } } catch (caught) { if (!cancelled) setError(caught instanceof Error ? caught.message : "Unable to load audit records."); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [page, q, sort, status]);
  return <main className="shell"><aside><Link className="brand" href="/">◆ GeM Verify</Link><p>WORKSPACE</p><Link href="/dashboard">Review queue</Link><Link href="/history">Audit history</Link><Link className="active" href="/audit">Audit records</Link><Link href="/settings">Settings</Link></aside><section className="workspace"><header><div><p className="eyebrow">IMMUTABLE EVIDENCE</p><h1>Audit records</h1></div></header><div className="toolbar"><input placeholder="Search action, result, or details" value={q} onChange={event => { setPage(1); setQ(event.target.value); }}/><select value={status} onChange={event => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option><option value="success">Success</option><option value="failed">Failed</option><option value="review">Review</option></select><select value={sort} onChange={event => setSort(event.target.value)}><option value="-created_at">Newest first</option><option value="created_at">Oldest first</option><option value="action">Action A–Z</option></select></div>{loading ? <p className="state">Loading audit records…</p> : error ? <p className="state error">{error}</p> : rows.length === 0 ? <p className="state">No audit records match those filters.</p> : <div className="records">{rows.map(row => <button className="record" key={row.id} onClick={() => setSelected(row)}><span><b>{row.action}</b><small>{row.user_email} · {new Date(row.created_at).toLocaleString()}</small></span><span className={`tag ${row.status}`}>{row.status}</span><em>{row.result || "View details"}</em></button>)}</div>}<div className="pager"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {meta.total_pages} · {meta.count} records</span><button disabled={page >= meta.total_pages} onClick={() => setPage(page + 1)}>Next</button></div>{selected && <div className="modal" role="dialog"><div><button className="close" onClick={() => setSelected(null)}>×</button><p className="eyebrow">AUDIT DETAIL</p><h2>{selected.action}</h2><p>{selected.description}</p><dl><dt>Status</dt><dd>{selected.status}</dd><dt>Result</dt><dd>{selected.result || "—"}</dd><dt>Metadata</dt><dd><pre>{JSON.stringify(selected.metadata, null, 2)}</pre></dd></dl></div></div>}</section></main>;
}
