# Generated by Django 5.2.1 on 2026-09-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=120)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('related_object', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='core.supabaseuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='history_his_user_id_687b7e_idx')],
            },
        ),
    ]
